version: "3"

name: nitter-xposter

services:
  nitter:
    image: ghcr.io/sekai-soft/nitter:master
    # container_name: nitter
    # ports:
    #   - "8080:80"
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./nitter-guest_accounts.json:/src/guest_accounts.json:Z,ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # network_mode: service:nitter-ts
  nitter-redis:
    image: redis:6-alpine
    # container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
  nitter-auth:
    build:
      context: nitter-auth
      dockerfile: Dockerfile
    container_name: nitter-auth
    stdin_open: true
    tty: true
  nitter-xposter:
    image: ghcr.io/k-t-corp/nitter-xposter:latest
    # container_name: nitter-xposter
    volumes:
      - nitter-xposter:/app/dbs
    environment:
      SQLITE_FILE: /app/dbs/db.db
      NITTER_HOST: nitter
      NITTER_HTTPS: 'false'
      TWITTER_HANDLE: ${TWITTER_HANDLE}
      MASTODON_HOST: ${MASTODON_HOST}
      MASTODON_CLIENT_ID: ${MASTODON_CLIENT_ID}
      MASTODON_CLIENT_SECRET: ${MASTODON_CLIENT_SECRET}
      MASTODON_ACCESS_TOKEN: ${MASTODON_ACCESS_TOKEN}
      MASTODON_STATUS_LIMIT: '10'
    restart: unless-stopped
  nitter-xposter-bsky:
    image: ghcr.io/k-t-corp/nitter-xposter:latest
    # container_name: nitter-xposter-bsky
    volumes:
      - nitter-xposter-bsky:/app/dbs
    environment:
      SQLITE_FILE: /app/dbs/db.db
      NITTER_HOST: nitter
      NITTER_HTTPS: 'false'
      TWITTER_HANDLE: ${TWITTER_HANDLE}
      BSKY_HANDLE: ${BSKY_HANDLE}
      BSKY_PASSWORD: ${BSKY_PASSWORD}
      BSKY_STATUS_LIMIT: '10'
      INTERVAL_MINUTES: '30'
    restart: unless-stopped
volumes:
  nitter-redis:
  nitter-xposter:
  nitter-xposter-bsky:
